// <auto-generated />
using System;
using ABOdds.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ABOdds.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BettingDbContext))]
    [Migration("20260905035118_PersistDiscordCooldown")]
    partial class PersistDiscordCooldown
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.AlertEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertStateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("EvOpportunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastDeliveryError")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RateLimitedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlertStateId");

                    b.HasIndex("EvOpportunityId");

                    b.HasIndex("RateLimitedUntilUtc")
                        .HasFilter("\"RateLimitedUntilUtc\" IS NOT NULL");

                    b.HasIndex("DeliveryStatus", "NextAttemptAtUtc");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.AlertStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookmakerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAlertedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastAlertedDecimalOdds")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal?>("LastAlertedExpectedValue")
                        .HasPrecision(20, 12)
                        .HasColumnType("numeric(20,12)");

                    b.Property<DateTimeOffset?>("LastDisappearedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LastSeenDecimalOdds")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("LastSeenExpectedValue")
                        .HasPrecision(20, 12)
                        .HasColumnType("numeric(20,12)");

                    b.Property<string>("LineKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("EventId", "MarketId", "SelectionKey", "LineKey", "BookmakerKey")
                        .IsUnique();

                    b.ToTable("alert_states", (string)null);
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.EvOpportunityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedValue")
                        .HasPrecision(20, 12)
                        .HasColumnType("numeric(20,12)");

                    b.Property<Guid>("FairValueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OddsSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollBatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("FairValueId");

                    b.HasIndex("OddsSnapshotId");

                    b.HasIndex("PollBatchId", "OddsSnapshotId")
                        .IsUnique();

                    b.ToTable("ev_opportunities", (string)null);
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CommenceTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SportKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CommenceTimeUtc");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.FairValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FairDecimalOdds")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("FairProbability")
                        .HasPrecision(20, 12)
                        .HasColumnType("numeric(20,12)");

                    b.Property<decimal?>("Line")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("LineKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollBatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReferenceBookCount")
                        .HasColumnType("integer");

                    b.Property<string>("SelectionDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SelectionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "CalculatedAtUtc");

                    b.HasIndex("PollBatchId", "MarketId", "SelectionKey", "LineKey")
                        .IsUnique();

                    b.ToTable("fair_values", (string)null);
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.MarketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Key", "Period")
                        .IsUnique();

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.OddsSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookmakerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BookmakerTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("DecimalOdds")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal?>("Line")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("LineKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PollBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectionDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SelectionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "SourceUpdatedAtUtc");

                    b.HasIndex("PollBatchId", "MarketId", "BookmakerKey", "SelectionKey", "LineKey")
                        .IsUnique();

                    b.ToTable("odds_snapshots", (string)null);
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.PollBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AlertRulesCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EvCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FairValueCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastFailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastFailedStage")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("QuotaRemaining")
                        .HasColumnType("integer");

                    b.Property<int?>("QuotaUsed")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestCost")
                        .HasColumnType("integer");

                    b.Property<string>("SportKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AlertRulesCompletedAtUtc", "ObservedAtUtc");

                    b.HasIndex("EvCompletedAtUtc", "ObservedAtUtc");

                    b.HasIndex("FairValueCompletedAtUtc", "ObservedAtUtc");

                    b.ToTable("poll_batches", (string)null);
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.AlertEntity", b =>
                {
                    b.HasOne("ABOdds.Infrastructure.Persistence.AlertStateEntity", "AlertState")
                        .WithMany("Alerts")
                        .HasForeignKey("AlertStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ABOdds.Infrastructure.Persistence.EvOpportunityEntity", "EvOpportunity")
                        .WithMany("Alerts")
                        .HasForeignKey("EvOpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlertState");

                    b.Navigation("EvOpportunity");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.AlertStateEntity", b =>
                {
                    b.HasOne("ABOdds.Infrastructure.Persistence.EventEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ABOdds.Infrastructure.Persistence.MarketEntity", "Market")
                        .WithMany("AlertStates")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.EvOpportunityEntity", b =>
                {
                    b.HasOne("ABOdds.Infrastructure.Persistence.FairValueEntity", "FairValue")
                        .WithMany("EvOpportunities")
                        .HasForeignKey("FairValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ABOdds.Infrastructure.Persistence.OddsSnapshotEntity", "OddsSnapshot")
                        .WithMany()
                        .HasForeignKey("OddsSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ABOdds.Infrastructure.Persistence.PollBatchEntity", "PollBatch")
                        .WithMany("EvOpportunities")
                        .HasForeignKey("PollBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FairValue");

                    b.Navigation("OddsSnapshot");

                    b.Navigation("PollBatch");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.FairValueEntity", b =>
                {
                    b.HasOne("ABOdds.Infrastructure.Persistence.MarketEntity", "Market")
                        .WithMany("FairValues")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ABOdds.Infrastructure.Persistence.PollBatchEntity", "PollBatch")
                        .WithMany("FairValues")
                        .HasForeignKey("PollBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("PollBatch");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.MarketEntity", b =>
                {
                    b.HasOne("ABOdds.Infrastructure.Persistence.EventEntity", "Event")
                        .WithMany("Markets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.OddsSnapshotEntity", b =>
                {
                    b.HasOne("ABOdds.Infrastructure.Persistence.MarketEntity", "Market")
                        .WithMany("OddsSnapshots")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ABOdds.Infrastructure.Persistence.PollBatchEntity", "PollBatch")
                        .WithMany("OddsSnapshots")
                        .HasForeignKey("PollBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("PollBatch");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.AlertStateEntity", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.EvOpportunityEntity", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.EventEntity", b =>
                {
                    b.Navigation("Markets");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.FairValueEntity", b =>
                {
                    b.Navigation("EvOpportunities");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.MarketEntity", b =>
                {
                    b.Navigation("AlertStates");

                    b.Navigation("FairValues");

                    b.Navigation("OddsSnapshots");
                });

            modelBuilder.Entity("ABOdds.Infrastructure.Persistence.PollBatchEntity", b =>
                {
                    b.Navigation("EvOpportunities");

                    b.Navigation("FairValues");

                    b.Navigation("OddsSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
